name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build-for-testing -project DebugKitExampleApp/DebugKitExampleApp.xcodeproj -scheme DebugKitExampleUIKit -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11"
    - name: Run tests
      run: xcodebuild test-without-building -project DebugKitExampleApp/DebugKitExampleApp.xcodeproj -scheme DebugKitExampleUIKit -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11"
